# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: "Deploy"
on:
  push:
    branches:
      - "main"
  workflow_dispatch:
permissions:
  contents: "read"
  pages: "write"
  id-token: "write"
concurrency:
  group: "pages"
  cancel-in-progress: false
jobs:
  main:
    name: "Main"
    runs-on: "ubuntu-latest"
    environment:
      name: "github-pages"
      url: "${{steps.deployment.outputs.page_url}}"
    steps:
      - name: "Checkout Repository"
        uses: "actions/checkout@v4.1.1"
      - name: "Configure GitHub Pages"
        uses: "actions/configure-pages@v4.0.0"
      - name: "Upload GitHub Pages Artifact"
        uses: "actions/upload-pages-artifact@v3.0.0"
        with:
          path: "schema/"
      - name: "Deploy To GitHub Pages"
        id: "deployment"
        uses: "actions/deploy-pages@v4.0.2"
